# Change these first
owner: zateckar # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: IdP
    url: $IDP_URL
  - name: OPP
    url: $OPP_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPP_KEY"
     - "Content-Type: application/json"
  - name: OPT
    url: $OPT_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPT_KEY"
     - "Content-Type: application/json"
  - name: OPD
    url: $OPD_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$D_KEY"
     - "Content-Type: application/json"
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/zateckar/status/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  theme: dark
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "6 */6 * * *"
  responseTime: "8 */6 * * *"
  staticSite: "1 1 * * *"
  summary: "6 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/6 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: ""
