# Change these first
owner: zateckar # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: IdP
    url: $IDP_URL
    icon: https://cdn0.iconfinder.com/data/icons/digital-identity-user/100/server_storage_identity_digital_user_electronic_document-64.png
  - name: OPP
    url: $OPP_URL
    icon: https://img.icons8.com/?size=100&id=SBEjRDmczSCC&format=png&color=000000
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPP_KEY"
  - name: OPT
    url: $OPT_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPT_KEY"
  - name: OPD
    url: $OPD_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$D_KEY"
  - name: AZP
    url: $AZP_URL
    icon: https://img.icons8.com/?size=100&id=SBEjRDmczSCC&format=png&color=000000
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPP_KEY"
  - name: AZT
    url: $AZT_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$OPT_KEY"
  - name: AZD
    url: $AZD_URL
    __dangerous__body_down_if_text_missing: 'pass'
    headers:
     - "$D_KEY"
  - name: Portal
    url: $PORTAL_URL
    icon: https://cdn2.iconfinder.com/data/icons/web-development-172/66/32_browser_web_browser_search_engine_internet_browser_internet_service_provider_portal-128.png
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/zateckar/status/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "6 */6 * * *"
  responseTime: "8 */6 * * *"
  staticSite: "1 1 * * *"
  summary: "6 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/6 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: ""
